### ISSUE TITLE
Error trying to add concierge-droid with gynoid

### ISSUE THREAD

**Issue by jotadepicas** [auth0/concierge-droid#19]
Hi! :)
Not sure if this should be a gynoid or concierge-droid issue. After starging gynoid bot and doing this:
```
@gynoid register concierge using [TOKEN]
@gynoid extend concierge from auth0/concierge-droid
```
I get the following error:

**An error has occured while extending a droid [TypeError: Cannot read property 'METRICS_API_KEY' of undefined]**

It seems as if `context.config` here is undefined? https://github.com/auth0/concierge-droid/blob/master/index.js#L8

This is the complete trace for the error:

```
Unhandled rejection TypeError: Cannot read property 'METRICS_API_KEY' of undefined
    at module.exports (/gynoid/droids/concierge-droid/index.js:8:46)
    at /gynoid/lib/droid-extend.js:56:23
    at Promise._execute (/gynoid/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/gynoid/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/gynoid/node_modules/bluebird/js/release/promise.js:79:10)
    at DroidExtend.extend (/gynoid/lib/droid-extend.js:44:10)
    at /gynoid/lib/gynoid.js:144:27
    at tryCatcher (/gynoid/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/gynoid/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/gynoid/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/gynoid/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/gynoid/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/gynoid/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/gynoid/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/gynoid/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by Verlic** [comment]
Oh yes, that's an issue. You need to add the METRICS_API_KEY before hand, we shouldn't require it. Gynoid has an `add key` command to do this. Or you can update the `gynoid.config.json` to include it this way:

```
{
 "keys": {
    "concierge": {
      "METRICS_API_KEY": "{DATADOG-KEY}"
    }
 },
 "droid": { ... }
}
```

Good to see you by the way :)

**Comment by dirceu** [comment]
![na na na na batmaan jp](https://media.giphy.com/media/13KIi656sALvdm/giphy.gif)

**Comment by Verlic** [comment]
Let us know how it goes, this PR should fix this and you don't need to use the metrics key

**Comment by jotadepicas** [comment]
Thanks guys! Works like a charm. Good to see you too :)
